### ISSUE TITLE
Bumping to CloudSuite 4

### ISSUE THREAD

**Issue by Xusine1131** [parsa-epfl/cloudsuite#395]
In order to tune the workloads, we rely on small tweaks.

We should make running and argument passing consistent by :
- [x] Data Caching pass docker_servers.txt for client as an argument instead of modifying it through docker #399 
- [x] Data Caching separate dataset and warmup to own container  #399 
- [x] Data Caching pure load  #399 
- [x] Data Caching pass argument total number of request to execute instead of infinite #399 
- [x] Data Serving separate warmup and load to different commands #398 
- [x] Data Serving add command to `compact` #398 
- [x] Media Streaming the log extraction argument
- [x] Media Streaming should print the connection rate.
- [x] Media Streaming friendly log #386 
- [x] Web Search separate dataset and uncompression
- [x] Web Search Simlink instead of copying #389
- [x] Web Search the tuning parameters should be given to the docker command
- [x] Web Search, and others Add argument to print or not to print log
- [x] Web Serving: delete the tar file after decompression #421 
- [x] Web Serving: don't copy, use symlink or similar instead #421 
- [x] Web Serving: merge changes suggested by Mike
- [x] In-memory and graph analytics separate master and worker in documents to match data analytics #416 
- [x] Fix the memory requirements for analytic workloads 16GB and if possible 32GB
- [x] #420
- [x] ~~Django workload~~ (deprecated) #397 
- [x] For data sets, offer option to either mount from docker image or to mount from folder to control destination directory

**Comment by UlisesLuzius** [comment]
Extra tasks:
[ ] Web Search, and others Add argument to print or not to print log

**Comment by Xusine1131** [comment]
Media streaming load generator:
- [ ] It should print the connection rate. (It did print in the image from cloudsuitetest, but it should be merged).

**Comment by Xusine1131** [comment]
Formatting:
- [ ] Putting the entry point of all containers to a fixed position. Now we have entry points like `/etc/docker-entrypoint` or `scripts/docker-entrypoint`.

**Comment by Xusine1131** [comment]
Analytics:
- [ ] Resource allocation for hadoop and Spark
